import 'dotenv/config';
import { Bot, InlineKeyboard, webhookCallback } from 'grammy';
import db, { ensureUser, getUsersForReminder, getDaySummary, todayForUser, toCents, fromCents } from '../server/db.js';
import { categoryList, createTransaction, getAccountOwned } from '../server/finance.js';
import { parseBankSms } from '../server/smsParse.js';
import { suggestCategory } from '../server/categorize.js';
import { pdfToImageDataUrls, extractPdfText } from '../server/pdfImages.js';
import { isGeminiEnabled, parseTransactionWithAI, parseReceiptImage, parseReceiptText, askBudgetAI } from '../server/gemini.js';
import { config } from '../server/config.js';

const token=config.botToken;
const pending=new Map();

function fmt(n){return new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n||0)+' ₽';}
function cats(userId){return categoryList(userId);}
function defaultAccount(userId){return db.prepare('SELECT * FROM accounts WHERE user_id=? ORDER BY id LIMIT 1').get(userId);}
function resolveCategory(userId,type,name){const list=cats(userId);const found=list.find(c=>c.type===type&&c.name.toLowerCase()===String(name||'').toLowerCase())||list.find(c=>c.type===type&&c.name==='Прочее')||list.find(c=>c.type===type);return {category_id:found?.id??null,category_name:found?.name||'Прочее'};}
function monthSummary(userId){const u=ensureUser(userId);const now=new Date();const from=new Date(now.getFullYear(),now.getMonth(),1);const to=new Date(now.getFullYear(),now.getMonth()+1,0);const f=from.toISOString().slice(0,10),t=to.toISOString().slice(0,10);const income=db.prepare("SELECT COALESCE(SUM(amount),0)t FROM transactions WHERE user_id=? AND type='income' AND kind='normal' AND date BETWEEN ? AND ?").get(userId,f,t).t;const expense=db.prepare("SELECT COALESCE(SUM(amount),0)t FROM transactions WHERE user_id=? AND type='expense' AND kind='normal' AND date BETWEEN ? AND ?").get(userId,f,t).t;const byCategory=db.prepare("SELECT c.name,SUM(t.amount)total FROM transactions t JOIN categories c ON c.id=t.category_id AND c.user_id=t.user_id WHERE t.user_id=? AND t.type='expense' AND t.kind='normal' AND t.date BETWEEN ? AND ? GROUP BY c.id ORDER BY total DESC LIMIT 8").all(userId,f,t).map(x=>({name:x.name,total:fromCents(x.total)}));const accounts=db.prepare('SELECT name,balance FROM accounts WHERE user_id=?').all(userId).map(x=>({name:x.name,balance:fromCents(x.balance)}));return {from:f,to:t,income:fromCents(income),expense:fromCents(expense),balance:fromCents(income-expense),byCategory,accounts,timezone:u.timezone};}

async function buildDraft(user,text){const list=cats(user.id);const sms=parseBankSms(text);if(sms){const sug=suggestCategory(`${sms.merchant||''} ${sms.raw||''}`,sms.type,list);return {...sms,...sug,note:String(sms.merchant||sms.raw||'').slice(0,120),date:sms.date||null,source:'sms'};}
 if(isGeminiEnabled()){const ai=await parseTransactionWithAI(text,list.map(c=>c.name));if(ai){const cat=resolveCategory(user.id,ai.type,ai.category_name);return {...ai,...cat};}}
 const m=String(text).match(/(\d+[\s\u00a0]?(?:[.,]\d{1,2})?)\s*(?:₽|р|руб|rub)?/i);if(!m)return null;const amount=Number(m[1].replace(/[\s\u00a0]/g,'').replace(',','.'));if(!Number.isFinite(amount)||amount<=0)return null;const type=/зарплат|получил|зачисл|аванс|премия/i.test(text)?'income':'expense';return {...resolveCategory(user.id,type,suggestCategory(text,type,list).category_name),amount,type,note:text.slice(0,120),date:null,source:'rules'};}

async function downloadFile(bot,fileId,max=7_000_000){const file=await bot.api.getFile(fileId);if(!file.file_path)throw new Error('Файл недоступен');const res=await fetch(`https://api.telegram.org/file/bot${token}/${file.file_path}`);if(!res.ok)throw new Error('Не удалось скачать файл');const buf=Buffer.from(await res.arrayBuffer());if(buf.length>max)throw new Error('Файл слишком большой');return {buf,filePath:file.file_path};}
async function offerDraft(ctx,draft){const key=`${ctx.from.id}:${ctx.update.update_id}`;pending.set(key,{...draft,tgId:ctx.from.id,createdAt:Date.now()});setTimeout(()=>pending.delete(key),30*60_000).unref();const sign=draft.type==='income'?'+':'−';const kb=new InlineKeyboard().text('✅ Записать',`tx:ok:${key}`).text('❌ Отмена',`tx:no:${key}`);await ctx.reply(`Распознано:\n${sign}${fmt(draft.amount)} · ${draft.type==='income'?'доход':'расход'}\n📂 ${draft.category_name||'—'}\n${draft.note?`📝 ${draft.note}\n`:''}\nЗаписать?`,{reply_markup:kb});}

function createBot(){if(!token){console.warn('BOT_TOKEN не задан — бот не запущен');return null;}const bot=new Bot(token);
 bot.command('start',async ctx=>{const name=ctx.from?.first_name||'друг';if(ctx.from?.id)ensureUser(ctx.from.id,name);const kb=config.webappUrl?new InlineKeyboard().webApp('💰 Открыть бюджет',config.webappUrl):undefined;await ctx.reply(`Привет, ${name}!\n\nПришлите SMS, текст вроде «кофе 350» или фото/PDF чека. Я предложу операцию перед записью.`,{reply_markup:kb});});
 bot.command('app',async ctx=>{if(!config.webappUrl)return ctx.reply('WEBAPP_URL не настроен');await ctx.reply('Откройте бюджет:',{reply_markup:new InlineKeyboard().webApp('💰 Открыть бюджет',config.webappUrl)});});
 bot.command('today',async ctx=>{if(!ctx.from?.id)return;const u=ensureUser(ctx.from.id,ctx.from.first_name||'');const s=getDaySummary(u.id,todayForUser(u));await ctx.reply(`📅 ${s.date}\nОпераций: ${s.count}\n+${fmt(s.income)} / −${fmt(s.expense)}`);});
 bot.command('ask',async ctx=>{if(!isGeminiEnabled())return ctx.reply('AI не настроен.');const u=ensureUser(ctx.from.id,ctx.from.first_name||'');const q=String(ctx.match||'').trim()||'Кратко оцени бюджет за месяц';await ctx.replyWithChatAction('typing');try{await ctx.reply((await askBudgetAI(q,monthSummary(u.id))).slice(0,3500));}catch(e){await ctx.reply('Не удалось получить ответ AI.');}});
 bot.command('remind',async ctx=>{const u=ensureUser(ctx.from.id,ctx.from.first_name||'');const a=String(ctx.match||'').trim().toLowerCase();if(a==='on'||a==='вкл'){db.prepare('UPDATE users SET remind_enabled=1 WHERE id=?').run(u.id);return ctx.reply('Напоминания включены.');}if(a==='off'||a==='выкл'){db.prepare('UPDATE users SET remind_enabled=0 WHERE id=?').run(u.id);return ctx.reply('Напоминания выключены.');}if(/^\d{1,2}$/.test(a)){const h=Number(a);if(h>23)return ctx.reply('Час от 0 до 23.');db.prepare('UPDATE users SET remind_hour=?,remind_enabled=1 WHERE id=?').run(h,u.id);return ctx.reply(`Напоминание в ${String(h).padStart(2,'0')}:00.`);}return ctx.reply('/remind on | off | 21');});
 bot.callbackQuery(/^tx:(ok|no):(.+)$/,async ctx=>{await ctx.answerCallbackQuery();const action=ctx.match[1],key=ctx.match[2],draft=pending.get(key);if(!draft||String(draft.tgId)!==String(ctx.from.id))return ctx.editMessageText('Черновик устарел.');if(action==='no'){pending.delete(key);return ctx.editMessageText('Отменено.');}try{const u=ensureUser(ctx.from.id,ctx.from.first_name||'');const acc=defaultAccount(u.id);createTransaction(u.id,{amount:draft.amount,type:draft.type,category_id:draft.category_id,account_id:acc?.id,note:draft.note||'',date:draft.date||todayForUser(u)});pending.delete(key);await ctx.editMessageText(`✅ ${draft.type==='income'?'+':'−'}${fmt(draft.amount)} · ${draft.category_name||''}`);}catch(e){await ctx.editMessageText('Не удалось записать операцию.');}});
 bot.on('message:photo',async ctx=>{if(!isGeminiEnabled())return ctx.reply('AI не настроен.');const u=ensureUser(ctx.from.id,ctx.from.first_name||'');await ctx.replyWithChatAction('typing');try{const p=ctx.message.photo.at(-1);const {buf}=await downloadFile(bot,p.file_id);const data=`data:image/jpeg;base64,${buf.toString('base64')}`;const g=await parseReceiptImage(data,cats(u.id).map(c=>c.name));if(!g)return ctx.reply('Не удалось прочитать чек.');await offerDraft(ctx,{...g,...resolveCategory(u.id,'expense',g.category_name),source:'receipt'});}catch(e){await ctx.reply('Не удалось обработать фото.');}});
 bot.on('message:document',async ctx=>{if(!isGeminiEnabled())return ctx.reply('AI не настроен.');const doc=ctx.message.document;const mime=(doc.mime_type||'').toLowerCase(),name=(doc.file_name||'').toLowerCase();const isImage=mime.startsWith('image/')||/\.(jpg|jpeg|png|webp)$/.test(name),isPdf=mime==='application/pdf'||name.endsWith('.pdf');if(!isImage&&!isPdf)return ctx.reply('Пришлите фото или PDF чека.');const u=ensureUser(ctx.from.id,ctx.from.first_name||'');await ctx.replyWithChatAction('typing');try{const {buf}=await downloadFile(bot,doc.file_id);let g=null;if(isImage){const ext=name.endsWith('.png')?'png':name.endsWith('.webp')?'webp':'jpeg';g=await parseReceiptImage(`data:image/${ext};base64,${buf.toString('base64')}`,cats(u.id).map(c=>c.name));}else{for(const img of pdfToImageDataUrls(buf,{maxImages:3,maxBytes:7_000_000})){g=await parseReceiptImage(img,cats(u.id).map(c=>c.name));if(g)break;}if(!g){const txt=extractPdfText(buf);if(txt.length>10)g=await parseReceiptText(txt,cats(u.id).map(c=>c.name));}}if(!g)return ctx.reply('Не удалось распознать документ.');await offerDraft(ctx,{...g,...resolveCategory(u.id,'expense',g.category_name)});}catch(e){await ctx.reply('Не удалось обработать документ.');}});
 bot.on('message:text',async ctx=>{const text=ctx.message.text||'';if(text.startsWith('/'))return;const u=ensureUser(ctx.from.id,ctx.from.first_name||'');try{const draft=await buildDraft(u,text);if(!draft)return ctx.reply('Не распознал операцию. Пример: «кофе 350».');await offerDraft(ctx,draft);}catch(e){await ctx.reply('Не удалось распознать сообщение.');}});
 bot.catch(err=>console.error('Bot error',err));return bot;}

let botInstance=null;
export function getBot(){return botInstance;}
export function getWebhookMiddleware(){return botInstance?webhookCallback(botInstance,'express'):null;}

export async function startBot(mode=config.botMode){if(!token)return null;botInstance=createBot();if(!botInstance)return null;try{await botInstance.api.setMyCommands([{command:'start',description:'Начать'},{command:'app',description:'Открыть бюджет'},{command:'today',description:'Сегодня'},{command:'ask',description:'Спросить AI'},{command:'remind',description:'Напоминания'}]);}catch(e){console.warn('setMyCommands',e.message)}
 if(mode==='polling'){await botInstance.api.deleteWebhook({drop_pending_updates:false}).catch(()=>{});botInstance.start({onStart:i=>console.log('Bot polling @'+i.username)});return botInstance;}
 if(!config.webappUrl||!config.webhookSecret){console.warn('WEBAPP_URL или TELEGRAM_WEBHOOK_SECRET не заданы — polling');await botInstance.api.deleteWebhook({drop_pending_updates:false}).catch(()=>{});botInstance.start({onStart:i=>console.log('Bot polling @'+i.username)});return botInstance;}
 const hook=`${config.webappUrl}/telegram-webhook`;try{await botInstance.api.setWebhook(hook,{secret_token:config.webhookSecret,drop_pending_updates:false,allowed_updates:['message','callback_query']});console.log('Webhook set:',hook);}catch(e){console.error('setWebhook failed:',e.message);await botInstance.api.deleteWebhook({drop_pending_updates:false}).catch(()=>{});botInstance.start({onStart:i=>console.log('Bot polling @'+i.username)});}return botInstance;}

export function startReminderScheduler(){if(!botInstance)return;setInterval(async()=>{const users=getUsersForReminder(new Date().getHours());for(const u of users){const today=todayForUser(u);if(u.last_reminder_date===today)continue;try{const s=getDaySummary(u.id,today);await botInstance.api.sendMessage(u.telegram_id,`📊 Итоги дня ${today}\nОпераций: ${s.count}\nДоход: +${fmt(s.income)}\nРасход: −${fmt(s.expense)}`);db.prepare('UPDATE users SET last_reminder_date=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').run(today,u.id);}catch(e){console.warn('Reminder failed',u.id,e.message);}}},60_000).unref();}

if(process.argv[1]?.endsWith('bot/index.js'))startBot(process.env.BOT_MODE||'polling').then(()=>startReminderScheduler()).catch(console.error);
